org.gradle.parallel=true
org.gradle.caching=true
systemProp.http.userAgent=Gradle
org.gradle.jvmargs=-Xmx6g -XX:+UseG1GC -XX:+ParallelRefProcEnabled

#aslib gitversion (you can change to "Dev-SNAPSHOT", for last versions)
#aslib_version=Release_1.20.1-SNAPSHOT #UNCOMMENT TO USE

#mod meta
mod_id=replace
mod_version=1.0-SNAPSHOT
mod_name=replace
mod_description=to be honest, write yourself in codegenerator (or files)
mod_authors=replace
mod_license=replace
mod_homepage=replace
mod_issues=
mod_icon=assets/modid?/icon.png

maven_group=replace
archives_base_name=i set modid idk lol prikol

#change if you want other version and.. BUT i dont really know will be work it

#minecraft data
java_version=17
minecraft_version=1.20.1

#mappings
mojang_mappings=1.20.1
parchment_mc_version=1.20.1
parchment_version=2023.09.03

#loaders settings
fabric_loom_version=1.13-SNAPSHOT
fabric_loader_version=0.15.11

forge_version=1.20.1-47.4.20
forge_gradle_version=[6.0,6.5)

neoforge_version=20.4.167
neoforge_gradle_version=2.0.173

#mixin
mixin_version=0.8.7
mixingradle_version=0.7-SNAPSHOT
mixinextras_version=0.4.1