modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="aslib"
version="1.0-SNAPSHOT"
displayName="AromaticSugarLibrary"
logoFile="icon.png"
authors="Akaize"
displayURL="https://github.com/Akfz/AsLib"
description="""
Come up with a joke yourself 
 Thanks SweetB1ans for help on start creation this mod"""

[[mixins]]
config="aslib.mixins.json"

[[dependencies.aslib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
    type="required"

[[dependencies.aslib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
    type="required"

