{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0.15.jar",
          "url": "DBuild-1.0.15.jar",
          "size": 120647,
          "sha512": "698edcb3f38ceb392d499dae74653718732024439e32c683d00da33ad88999dd4ce5ce9bb09e2baf73d573a35fd27c00672c6b9eab7eaa9a6551b0dcdd2788ba",
          "sha256": "650ea8c58126533aceaca54a09abc840d67c6722bd8ad5f4fbf0fb9135f12bba",
          "sha1": "13db6abd5e4f68d2084f80eca62564e60656277e",
          "md5": "fb1538fb6da51bd67de33dd0ac1eca68"
        }
      ]
    }
  ]
}
