{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0.16.jar",
          "url": "DBuild-1.0.16.jar",
          "size": 121017,
          "sha512": "ebfce3bf475509d97b4a65a0e0d7d9e73a01ad3b8e3157160f9fd688b8182de7d4f268179c153def01f62529693b9bf119f16703ebb2696c14711c073626a639",
          "sha256": "98109605316afd389cf7b957a27905bc4a0afd7deecc0a57a45c7a26f0c35a08",
          "sha1": "a5e7425dc1904d0e458199d158049c21dd82be1b",
          "md5": "76ce1d7f35323c9451a823979c1a13ff"
        }
      ]
    }
  ]
}
