{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0-SNAPSHOT.jar",
          "url": "DBuild-1.0-SNAPSHOT.jar",
          "size": 120647,
          "sha512": "748040d473332f76b385c4899bdb1bbb4ddeb10ba8974efdf932a919b7fbc9c4af607a82362ec690813b2006b6046afd9897c3f26b020e75204a44446fb26bce",
          "sha256": "ff12ad654bd7c07ac2db0034e1a7e3afbb345f43490486736f2a23bf4e503580",
          "sha1": "fd64566c7fe55e10d353095142b5021484179d1f",
          "md5": "e2f96d7bb3b9d13b09cab49087c73f61"
        }
      ]
    }
  ]
}
