{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0-SNAPSHOT.jar",
          "url": "DBuild-1.0-SNAPSHOT.jar",
          "size": 117770,
          "sha512": "dccfdab7d8b3bd3f538962a027dff372c79fb902ffcf7e19d49a70481050db9201f56b7f2728d69d7130dc060de3239461b79361400b71f751393903630f8342",
          "sha256": "b072bce67da194cf200cd5eedd24836e70e05e77915f31b735feaec8203744de",
          "sha1": "c8ed02821d7a270de04f90f63089531b940815f9",
          "md5": "86e8e8135276caa58b08e14eec9d63e2"
        }
      ]
    }
  ]
}
