{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0-SNAPSHOT.jar",
          "url": "DBuild-1.0-SNAPSHOT.jar",
          "size": 120647,
          "sha512": "65c6cd31732692f4b4e46957bb5891e9f881f74b0dba2af3b63ca7d6ac68153f92115ec75e722ac66c3a30f6ffae8b6dbc5983ef40a5814997b5c5b33b34ab62",
          "sha256": "4113c0a4461a60d5aaba04b07cfa89d155bd23fd9dfdd0ddc7f3f7c520e3dee4",
          "sha1": "0512d55449254281dd2ebbcc88af5e06f367f394",
          "md5": "78a9b01eca91f00a994cb55336f9318c"
        }
      ]
    }
  ]
}
