{
  "formatVersion": "1.1",
  "component": {
    "group": "v.akfz",
    "module": "DBuild",
    "version": "1.0.17",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.4"
    }
  },
  "variants": [
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "DBuild-1.0.17.jar",
          "url": "DBuild-1.0.17.jar",
          "size": 116670,
          "sha512": "5fd88505c70337b221b3643e1b6327817f24d8e0d08e8bcc2a0a871ad76fba8ab024037218c9b6fe8be1bcf849a37ddf3f0758d5a63b2092df4df122266a33a9",
          "sha256": "259e0c93e5979629fea84e59137ee82d53f87d7975e98c0f354cc5b0c8f221b3",
          "sha1": "2781f33e60ff6d25e926a74a492e16e15caee2be",
          "md5": "ec7a72bb12715a5f1153d4b5c30442e3"
        }
      ]
    }
  ]
}
